//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLayer.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoLayer.Resources.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entity for object &apos;{0}&apos; not found..
        /// </summary>
        internal static string EntityNotFoundError {
            get {
                return ResourceManager.GetString("EntityNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to convert &apos;{0}&apos; entity to &apos;{1}&apos; model - properties differ..
        /// </summary>
        internal static string EntityToModelError {
            get {
                return ResourceManager.GetString("EntityToModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to execute sql query: {0}.
        /// </summary>
        internal static string ExecuteSqlRawError {
            get {
                return ResourceManager.GetString("ExecuteSqlRawError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Page number and page size must be greater than 0..
        /// </summary>
        internal static string GetPageError {
            get {
                return ResourceManager.GetString("GetPageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to convert &apos;{0}&apos; model to &apos;{1}&apos; entity - properties differ..
        /// </summary>
        internal static string ModelToEntityError {
            get {
                return ResourceManager.GetString("ModelToEntityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Identifier must be greater than 0..
        /// </summary>
        internal static string NonPositiveIdError {
            get {
                return ResourceManager.GetString("NonPositiveIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entity &apos;{0}&apos; cannot be null..
        /// </summary>
        internal static string NullEntityError {
            get {
                return ResourceManager.GetString("NullEntityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collection &apos;{0}&apos; contains null entity..
        /// </summary>
        internal static string NullEntityInCollectionError {
            get {
                return ResourceManager.GetString("NullEntityInCollectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Primary key values cannot be null..
        /// </summary>
        internal static string NullPrimaryKeyError {
            get {
                return ResourceManager.GetString("NullPrimaryKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SQL query cannot be null..
        /// </summary>
        internal static string NullSqlQueryError {
            get {
                return ResourceManager.GetString("NullSqlQueryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred while executing the transaction: {0}.
        /// </summary>
        internal static string TransactionError {
            get {
                return ResourceManager.GetString("TransactionError", resourceCulture);
            }
        }
    }
}
